### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by muthiyanbhushan** [mratsim/McKinsey-SmartCities-Traffic-Prediction#1]
Hello,

I would like to know if the dataset is available opensource?

Thank you.

**Comment by mratsim** [comment]
Hello,

Sorry I completely missed your comment.

I don't think it is. You might be able to get it by registering to AnalyticsVidhya, and go on the competition page: https://datahack.analyticsvidhya.com/contest/mckinsey-analytics-hackathon/
